"""add_categories_drop_subcategory

Revision ID: 0d44c4e12b6a
Revises: 05dc4bdbdc58
Create Date: 2026-03-22 00:02:23.243150

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d44c4e12b6a'
down_revision: str | None = '05dc4bdbdc58'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=64), nullable=False))
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('categories', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('categories', 'emoji',
               existing_type=sa.VARCHAR(length=8),
               server_default='🔖',
               existing_nullable=False)
    op.drop_constraint(op.f('categories_key_key'), 'categories', type_='unique')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_column('categories', 'key')
    # Drop subcategory column from telegram_chats
    op.drop_column('telegram_chats', 'subcategory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('key', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_unique_constraint(op.f('categories_key_key'), 'categories', ['key'], postgresql_nulls_not_distinct=False)
    op.alter_column('categories', 'emoji',
               existing_type=sa.VARCHAR(length=8),
               server_default=None,
               existing_nullable=False)
    op.drop_column('categories', 'sort_order')
    op.drop_column('categories', 'is_active')
    op.drop_column('categories', 'slug')
    op.add_column('telegram_chats', sa.Column('subcategory', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###
