"""add_complaint_blacklist_fields_to_telegram_chats

Revision ID: 96d841a6c242
Revises: a1b2c3d4e5f7
Create Date: 2026-03-03 19:58:14.313959+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96d841a6c242"
down_revision: str | None = "a1b2c3d4e5f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_chats",
        sa.Column("complaint_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "telegram_chats", sa.Column("last_complaint_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "telegram_chats",
        sa.Column("is_blacklisted", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "telegram_chats", sa.Column("blacklisted_reason", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "telegram_chats", sa.Column("blacklisted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "telegram_chats",
        sa.Column("consecutive_failures", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index(
        op.f("ix_telegram_chats_is_blacklisted"), "telegram_chats", ["is_blacklisted"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telegram_chats_is_blacklisted"), table_name="telegram_chats")
    op.drop_column("telegram_chats", "consecutive_failures")
    op.drop_column("telegram_chats", "blacklisted_at")
    op.drop_column("telegram_chats", "blacklisted_reason")
    op.drop_column("telegram_chats", "is_blacklisted")
    op.drop_column("telegram_chats", "last_complaint_at")
    op.drop_column("telegram_chats", "complaint_count")
    # ### end Alembic commands ###
