"""add_review_model

Revision ID: 20260307_140000
Revises: 20260307_120000
Create Date: 2026-03-07 14:00:00.000000+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20260307_140000'
down_revision: str | None = '20260307_120000'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'reviews',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('reviewer_id', sa.BigInteger(), nullable=False),
        sa.Column('reviewee_id', sa.BigInteger(), nullable=False),
        sa.Column('channel_id', sa.BigInteger(), nullable=True),
        sa.Column('placement_id', sa.Integer(), nullable=False),
        sa.Column('reviewer_role', sa.String(length=20), nullable=False),
        sa.Column('score_compliance', sa.Integer(), nullable=True),
        sa.Column('score_audience', sa.Integer(), nullable=True),
        sa.Column('score_speed', sa.Integer(), nullable=True),
        sa.Column('score_material', sa.Integer(), nullable=True),
        sa.Column('score_requirements', sa.Integer(), nullable=True),
        sa.Column('score_payment', sa.Integer(), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('is_hidden', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['channel_id'], ['telegram_chats.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['placement_id'], ['mailing_logs.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('reviewer_id', 'placement_id', name='uq_reviewer_placement'),
    )
    op.create_index('ix_reviews_reviewer_id', 'reviews', ['reviewer_id'], unique=False)
    op.create_index('ix_reviews_reviewee_id', 'reviews', ['reviewee_id'], unique=False)
    op.create_index('ix_reviews_channel_id', 'reviews', ['channel_id'], unique=False)
    op.create_index('ix_reviews_placement_id', 'reviews', ['placement_id'], unique=True)
    op.create_index('ix_reviews_is_hidden', 'reviews', ['is_hidden'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_is_hidden', table_name='reviews')
    op.drop_index('ix_reviews_placement_id', table_name='reviews')
    op.drop_index('ix_reviews_channel_id', table_name='reviews')
    op.drop_index('ix_reviews_reviewee_id', table_name='reviews')
    op.drop_index('ix_reviews_reviewer_id', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
