"""add_gamification_fields_and_badge_models

Revision ID: 20260307_170000
Revises: 20260307_160000
Create Date: 2026-03-07 17:00:00.000000+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260307_170000"
down_revision: str | None = "20260307_160000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем поля геймификации в users
    op.add_column("users", sa.Column("level", sa.Integer(), nullable=False, server_default="1"))
    op.add_column("users", sa.Column("xp_points", sa.Integer(), nullable=False, server_default="0"))
    op.add_column(
        "users",
        sa.Column(
            "total_spent", sa.Numeric(precision=12, scale=2), nullable=False, server_default="0.00"
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "total_earned", sa.Numeric(precision=12, scale=2), nullable=False, server_default="0.00"
        ),
    )
    op.add_column(
        "users", sa.Column("streak_days", sa.Integer(), nullable=False, server_default="0")
    )

    # Создаём таблицу badges
    op.create_table(
        "badges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("icon_emoji", sa.String(length=10), nullable=False),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("condition_type", sa.String(length=30), nullable=False),
        sa.Column("condition_value", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_badges_code", "badges", ["code"], unique=True)

    # Создаём таблицу user_badges
    op.create_table(
        "user_badges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("badge_id", sa.Integer(), nullable=False),
        sa.Column("earned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["badge_id"], ["badges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "badge_id", name="uq_user_badge"),
    )
    op.create_index("ix_user_badges_user_id", "user_badges", ["user_id"], unique=False)
    op.create_index("ix_user_badges_badge_id", "user_badges", ["badge_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_badges_badge_id", table_name="user_badges")
    op.drop_index("ix_user_badges_user_id", table_name="user_badges")
    op.drop_table("user_badges")
    op.drop_index("ix_badges_code", table_name="badges")
    op.drop_table("badges")
    op.drop_column("users", "streak_days")
    op.drop_column("users", "total_earned")
    op.drop_column("users", "total_spent")
    op.drop_column("users", "xp_points")
    op.drop_column("users", "level")
    # ### end Alembic commands ###
