"""add_opt_in_fields_to_telegram_chat

Revision ID: 20260306_120000
Revises: a1b2c3d4e5f8
Create Date: 2026-03-06 12:00:00.000000+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260306_120000"
down_revision: str | None = "a1b2c3d4e5f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем поля opt-in для Спринта 0
    op.add_column(
        "telegram_chats",
        sa.Column("bot_is_admin", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "telegram_chats", sa.Column("admin_added_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("telegram_chats", sa.Column("owner_user_id", sa.BigInteger(), nullable=True))
    op.add_column("telegram_chats", sa.Column("price_per_post", sa.Numeric(10, 2), nullable=True))
    op.add_column(
        "telegram_chats",
        sa.Column("is_accepting_ads", sa.Boolean(), nullable=False, server_default="false"),
    )

    # Создаём foreign key для owner_user_id
    op.create_foreign_key(
        "fk_telegram_chats_owner_user_id",
        "telegram_chats",
        "users",
        ["owner_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_telegram_chats_owner_user_id", "telegram_chats", type_="foreignkey")
    op.drop_column("telegram_chats", "is_accepting_ads")
    op.drop_column("telegram_chats", "price_per_post")
    op.drop_column("telegram_chats", "owner_user_id")
    op.drop_column("telegram_chats", "admin_added_at")
    op.drop_column("telegram_chats", "bot_is_admin")
    # ### end Alembic commands ###
