"""add channel mediakit model

Revision ID: 0013
Revises: 0012
Create Date: 2026-03-09 01:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_mediakits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("custom_description", sa.String(2000), nullable=True),
        sa.Column("logo_file_id", sa.String(255), nullable=True),
        sa.Column("banner_file_id", sa.String(255), nullable=True),
        sa.Column("show_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("theme_color", sa.String(7), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("downloads_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["channel_id"], ["telegram_chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Индексы
    op.create_index(
        "ix_channel_mediakits_channel_id", "channel_mediakits", ["channel_id"], unique=True
    )
    op.create_index("ix_channel_mediakits_owner_id", "channel_mediakits", ["owner_user_id"])
    op.create_index("ix_channel_mediakits_is_public", "channel_mediakits", ["is_public"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_channel_mediakits_is_public", table_name="channel_mediakits")
    op.drop_index("ix_channel_mediakits_owner_id", table_name="channel_mediakits")
    op.drop_index("ix_channel_mediakits_channel_id", table_name="channel_mediakits")
    op.drop_table("channel_mediakits")
    # ### end Alembic commands ###
