"""add yookassa_payment table

Revision ID: 008
Revises: 007
Create Date: 2026-03-11

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '008'
down_revision: str | None = '007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.create_table(
        'yookassa_payment',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('payment_id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('amount_rub', sa.Numeric(10, 2), nullable=False),
        sa.Column('credits', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, server_default='pending'),
        sa.Column('description', sa.String(255), nullable=True),
        sa.Column('confirmation_url', sa.String(512), nullable=True),
        sa.Column('idempotency_key', sa.String(36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_yookassa_payment_payment_id', 'yookassa_payment', ['payment_id'], unique=True)
    op.create_index('ix_yookassa_payment_user_id', 'yookassa_payment', ['user_id'])
    op.create_index('ix_yookassa_payment_status', 'yookassa_payment', ['status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_index('ix_yookassa_payment_status', table_name='yookassa_payment')
    op.drop_index('ix_yookassa_payment_user_id', table_name='yookassa_payment')
    op.drop_index('ix_yookassa_payment_payment_id', table_name='yookassa_payment')
    op.drop_table('yookassa_payment')
    # ### end Alembic commands ###
