"""add badge achievements and badge rewards

Revision ID: 0012
Revises: 0011
Create Date: 2026-03-09 00:30:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0012'
down_revision: str | None = '0011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Добавляем поля в таблицу badges
    op.add_column('badges', sa.Column('credits_reward', sa.Integer(),
                                      nullable=False, server_default='0'))
    op.add_column('badges', sa.Column('is_rare', sa.Boolean(),
                                      nullable=False, server_default='false'))
    op.add_column('badges', sa.Column('is_active', sa.Boolean(),
                                      nullable=False, server_default='true'))

    # 2. Создаём таблицу badge_achievements
    op.create_table('badge_achievements',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('badge_id', sa.Integer(), nullable=False),
                    sa.Column('achievement_type', sa.String(50), nullable=False),
                    sa.Column('threshold', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False,
                              server_default='true'),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'))

    # 3. Создаём индексы
    op.create_index('ix_badge_achievements_type', 'badge_achievements', ['achievement_type'])  # noqa: E501
    op.create_index('ix_badge_achievements_active', 'badge_achievements', ['is_active'])  # noqa: E501

    # 4. Добавляем seed данные - базовые достижения
    sa.table(
        'badge_achievements',
        sa.column('badge_id', sa.Integer()),
        sa.column('achievement_type', sa.String()),
        sa.column('threshold', sa.Integer()),
        sa.column('description', sa.Text()),
        sa.column('is_active', sa.Boolean()),
    )

    # Вставляем достижения (badge_id будут проставлены после создания значков)
    # Для now оставляем пустым - значки создаются через seed скрипт
    # op.bulk_insert(badge_achievements_table, [...])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_badge_achievements_active', table_name='badge_achievements')
    op.drop_index('ix_badge_achievements_type', table_name='badge_achievements')
    op.drop_table('badge_achievements')

    op.drop_column('badges', 'is_active')
    op.drop_column('badges', 'is_rare')
    op.drop_column('badges', 'credits_reward')
    # ### end Alembic commands ###
