"""payout_requests_v42

Revision ID: 014
Revises: 013
Create Date: 2026-03-13

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "014"
down_revision: str | None = "013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    # Add v4.2 payout fields (gross/fee/net/tax_withheld)
    op.add_column("payouts", sa.Column("gross_amount", sa.Numeric(12, 2), nullable=True))
    op.add_column("payouts", sa.Column("fee_amount", sa.Numeric(12, 2), nullable=True))
    op.add_column("payouts", sa.Column("net_amount", sa.Numeric(12, 2), nullable=True))
    op.add_column("payouts", sa.Column("tax_withheld", sa.Numeric(12, 2), nullable=True))

    # Backfill existing records: gross=amount, fee=0, net=amount
    op.execute("""
        UPDATE payouts
        SET gross_amount = amount,
            fee_amount = 0,
            net_amount = amount
        WHERE gross_amount IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_column("payouts", "gross_amount")
    op.drop_column("payouts", "fee_amount")
    op.drop_column("payouts", "net_amount")
    op.drop_column("payouts", "tax_withheld")
    # ### end Alembic commands ###
