"""add_payout_model

Revision ID: 20260307_100000
Revises: 20260306_120000
Create Date: 2026-03-07 10:00:00.000000+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20260307_100000'
down_revision: str | None = '20260306_120000'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'payouts',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('owner_id', sa.BigInteger(), nullable=False),
        sa.Column('channel_id', sa.BigInteger(), nullable=False),
        sa.Column('placement_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=10), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('wallet_address', sa.String(length=200), nullable=True),
        sa.Column('tx_hash', sa.String(length=200), nullable=True),
        sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['channel_id'], ['telegram_chats.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['placement_id'], ['mailing_logs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_payouts_owner_id', 'payouts', ['owner_id'], unique=False)
    op.create_index('ix_payouts_channel_id', 'payouts', ['channel_id'], unique=False)
    op.create_index('ix_payouts_placement_id', 'payouts', ['placement_id'], unique=True)
    op.create_index('ix_payouts_status', 'payouts', ['status'], unique=False)
    op.create_index('ix_payouts_paid_at', 'payouts', ['paid_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payouts_paid_at', table_name='payouts')
    op.drop_index('ix_payouts_status', table_name='payouts')
    op.drop_index('ix_payouts_placement_id', table_name='payouts')
    op.drop_index('ix_payouts_channel_id', table_name='payouts')
    op.drop_index('ix_payouts_owner_id', table_name='payouts')
    op.drop_table('payouts')
    # ### end Alembic commands ###
