"""add balance_rub and earned_rub to users

Revision ID: 012
Revises: 74ca23ceb6d4
Create Date: 2026-03-12

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '012'
down_revision: str | None = '74ca23ceb6d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    # Add balance_rub column for ruble balance (placements)
    op.add_column(
        'users',
        sa.Column('balance_rub', sa.Numeric(12, 2), nullable=False, server_default='0.00')
    )
    
    # Add earned_rub column for owner earnings
    op.add_column(
        'users',
        sa.Column('earned_rub', sa.Numeric(12, 2), nullable=False, server_default='0.00')
    )
    
    # Add check constraints
    op.create_check_constraint(
        'ck_users_balance_rub_positive',
        'users',
        'balance_rub >= 0'
    )
    op.create_check_constraint(
        'ck_users_earned_rub_positive',
        'users',
        'earned_rub >= 0'
    )
    
    # Migrate existing balance data to balance_rub if exists
    op.execute("""
        UPDATE users 
        SET balance_rub = COALESCE(balance, 0.00)
        WHERE balance IS NOT NULL
    """)
    
    # Make legacy balance nullable (already done in model)
    op.alter_column('users', 'balance', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    # Migrate data back from balance_rub to balance
    op.execute("""
        UPDATE users 
        SET balance = balance_rub
        WHERE balance_rub IS NOT NULL
    """)
    
    op.drop_constraint('ck_users_earned_rub_positive', 'users', type_='check')
    op.drop_constraint('ck_users_balance_rub_positive', 'users', type_='check')
    op.drop_column('users', 'earned_rub')
    op.drop_column('users', 'balance_rub')
    # ### end Alembic commands ###
