"""add_notifications_enabled_to_users

Revision ID: b377ebf742bf
Revises: 96d841a6c242
Create Date: 2026-03-03 20:22:39.615474+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b377ebf742bf'
down_revision: str | None = '96d841a6c242'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_chats', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('telegram_chats', 'russian_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('telegram_chats', 'complaint_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('telegram_chats', 'is_blacklisted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('telegram_chats', 'consecutive_failures',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_telegram_chats_language'), table_name='telegram_chats')
    op.drop_index(op.f('ix_telegram_chats_russian_score'), table_name='telegram_chats')
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_enabled')
    op.create_index(op.f('ix_telegram_chats_russian_score'), 'telegram_chats', ['russian_score'], unique=False)
    op.create_index(op.f('ix_telegram_chats_language'), 'telegram_chats', ['language'], unique=False)
    op.alter_column('telegram_chats', 'consecutive_failures',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('telegram_chats', 'is_blacklisted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('telegram_chats', 'complaint_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('telegram_chats', 'russian_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'1'::double precision"),
               existing_nullable=False)
    op.alter_column('telegram_chats', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'ru'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
