"""add terms_accepted_at to users

Revision ID: 009
Revises: 74ca23ceb6d4
Create Date: 2026-03-12

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '009'
down_revision: str | None = '74ca23ceb6d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.add_column(
        'users',
        sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_column('users', 'terms_accepted_at')
    # ### end Alembic commands ###
