"""add_llm_classification_fields_to_telegram_chats

Revision ID: a1b2c3d4e5f8
Revises: 96d841a6c242
Create Date: 2026-03-04 06:00:00.000000+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f8"
down_revision: str | None = "96d841a6c242"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_chats", sa.Column("last_classified_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("telegram_chats", sa.Column("llm_confidence", sa.Float(), nullable=True))
    op.add_column("telegram_chats", sa.Column("recent_posts", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_chats", "recent_posts")
    op.drop_column("telegram_chats", "llm_confidence")
    op.drop_column("telegram_chats", "last_classified_at")
    # ### end Alembic commands ###
