"""add_ctr_tracking_fields_to_campaign

Revision ID: 20260307_150000
Revises: 20260307_140000
Create Date: 2026-03-07 15:00:00.000000+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20260307_150000'
down_revision: str | None = '20260307_140000'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('tracking_url', sa.String(length=2048), nullable=True))
    op.add_column('campaigns', sa.Column('tracking_short_code', sa.String(length=20), nullable=True))
    op.add_column('campaigns', sa.Column('clicks_count', sa.Integer(), nullable=False, server_default='0'))
    op.create_index('ix_campaigns_tracking_short_code', 'campaigns', ['tracking_short_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_campaigns_tracking_short_code', table_name='campaigns')
    op.drop_column('campaigns', 'clicks_count')
    op.drop_column('campaigns', 'tracking_short_code')
    op.drop_column('campaigns', 'tracking_url')
    # ### end Alembic commands ###
