"""placement_requests_v42

Revision ID: 015
Revises: 014
Create Date: 2026-03-13

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '015'
down_revision: str | None = '014'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    # Add v4.2 publication format fields
    op.add_column('placement_requests', sa.Column('publication_format', sa.String(20), nullable=False, server_default='post_24h'))
    op.add_column('placement_requests', sa.Column('message_id', sa.BigInteger, nullable=True))
    op.add_column('placement_requests', sa.Column('scheduled_delete_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('placement_requests', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_column('placement_requests', 'publication_format')
    op.drop_column('placement_requests', 'message_id')
    op.drop_column('placement_requests', 'scheduled_delete_at')
    op.drop_column('placement_requests', 'deleted_at')
    # ### end Alembic commands ###
