"""make payout placement_id nullable

Revision ID: 0011
Revises: 0010
Create Date: 2026-03-09 00:10:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: str | None = '0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make placement_id nullable (no unique constraint to drop)
    op.alter_column('payouts', 'placement_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payouts', 'placement_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_unique_constraint('uq_payouts_placement_id', 'payouts', ['placement_id'])
    # ### end Alembic commands ###
