"""add pay_url to crypto_payments

Revision ID: b5189b613b29
Revises: 20260301_120000
Create Date: 2026-03-01 20:11:11.124778+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5189b613b29"
down_revision: str | None = "20260301_120000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("crypto_payments", sa.Column("pay_url", sa.String(length=512), nullable=True))
    op.alter_column("crypto_payments", "bonus_credits", existing_type=sa.INTEGER(), nullable=False)
    op.create_table_comment(
        "crypto_payments",
        "Крипто-платежи (CryptoBot / Telegram Stars)",
        existing_comment=None,
        schema=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        "crypto_payments",
        existing_comment="Крипто-платежи (CryptoBot / Telegram Stars)",
        schema=None,
    )
    op.alter_column("crypto_payments", "bonus_credits", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("crypto_payments", "pay_url")
    # ### end Alembic commands ###
