"""add_subcategory_to_telegram_chats

Revision ID: dfdd56ff6602
Revises: b5189b613b29
Create Date: 2026-03-02 16:36:39.524701+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfdd56ff6602'
down_revision: Union[str, None] = 'b5189b613b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_chats', sa.Column('subcategory', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_telegram_chats_subcategory'), 'telegram_chats', ['subcategory'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_chats_subcategory'), table_name='telegram_chats')
    op.drop_column('telegram_chats', 'subcategory')
    # ### end Alembic commands ###
