"""add is_admin to users

Revision ID: 007
Revises: a1b2c3d4e5f6
Create Date: 2026-03-11

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "007"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.add_column(
        "users", sa.Column("is_admin", sa.Boolean(), nullable=False, server_default="false")
    )

    # Create index for faster admin lookups
    op.create_index("ix_users_is_admin", "users", ["is_admin"])

    # Note: Backfill для существующих админов не требуется —
    # is_admin выставляется автоматически при следующем /start через settings.admin_ids
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_index("ix_users_is_admin", table_name="users")
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
