"""channel_settings_v42

Revision ID: 016
Revises: 015
Create Date: 2026-03-13

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "016"
down_revision: str | None = "015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    # Create channel_settings table if it doesn't exist (missing from initial schema)
    from alembic import op
    from sqlalchemy import inspect

    conn = op.get_bind()
    inspector = inspect(conn)

    if "channel_settings" not in inspector.get_table_names():
        op.create_table(
            "channel_settings",
            sa.Column("channel_id", sa.Integer(), nullable=False),
            sa.Column("owner_id", sa.Integer(), nullable=False),
            sa.Column("price_per_post", sa.Numeric(10, 2), nullable=False),
            sa.Column("daily_package_enabled", sa.Boolean(), nullable=False, server_default="true"),
            sa.Column("daily_package_max", sa.Integer(), nullable=False, server_default="2"),
            sa.Column("daily_package_discount", sa.Integer(), nullable=False, server_default="20"),
            sa.Column(
                "weekly_package_enabled", sa.Boolean(), nullable=False, server_default="true"
            ),
            sa.Column("weekly_package_max", sa.Integer(), nullable=False, server_default="5"),
            sa.Column("weekly_package_discount", sa.Integer(), nullable=False, server_default="30"),
            sa.Column("subscription_enabled", sa.Boolean(), nullable=False, server_default="true"),
            sa.Column("subscription_min_days", sa.Integer(), nullable=False, server_default="7"),
            sa.Column("subscription_max_days", sa.Integer(), nullable=False, server_default="365"),
            sa.Column("subscription_max_per_day", sa.Integer(), nullable=False, server_default="1"),
            sa.Column("publish_start_time", sa.Time(), nullable=False, server_default="09:00:00"),
            sa.Column("publish_end_time", sa.Time(), nullable=False, server_default="21:00:00"),
            sa.Column("break_start_time", sa.Time(), nullable=True),
            sa.Column("break_end_time", sa.Time(), nullable=True),
            sa.Column("auto_accept_enabled", sa.Boolean(), nullable=False, server_default="false"),
            sa.Column("auto_accept_min_price", sa.Numeric(10, 2), nullable=True),
            sa.Column("allow_format_post_24h", sa.Boolean(), nullable=False, server_default="true"),
            sa.Column("allow_format_post_48h", sa.Boolean(), nullable=False, server_default="true"),
            sa.Column("allow_format_post_7d", sa.Boolean(), nullable=False, server_default="false"),
            sa.Column("allow_format_pin_24h", sa.Boolean(), nullable=False, server_default="false"),
            sa.Column("allow_format_pin_48h", sa.Boolean(), nullable=False, server_default="false"),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            ),
            sa.ForeignKeyConstraint(["channel_id"], ["telegram_chats.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("channel_id"),
            comment="Настройки монетизации каналов (one-to-one с telegram_chats)",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_column("channel_settings", "allow_format_post_24h")
    op.drop_column("channel_settings", "allow_format_post_48h")
    op.drop_column("channel_settings", "allow_format_post_7d")
    op.drop_column("channel_settings", "allow_format_pin_24h")
    op.drop_column("channel_settings", "allow_format_pin_48h")
    # ### end Alembic commands ###
