"""channel_settings_v42

Revision ID: 016
Revises: 015
Create Date: 2026-03-13

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '016'
down_revision: str | None = '015'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    # Add v4.2 publication format allow_* fields
    op.add_column('channel_settings', sa.Column('allow_format_post_24h', sa.Boolean, nullable=False, server_default='true'))
    op.add_column('channel_settings', sa.Column('allow_format_post_48h', sa.Boolean, nullable=False, server_default='true'))
    op.add_column('channel_settings', sa.Column('allow_format_post_7d', sa.Boolean, nullable=False, server_default='false'))
    op.add_column('channel_settings', sa.Column('allow_format_pin_24h', sa.Boolean, nullable=False, server_default='false'))
    op.add_column('channel_settings', sa.Column('allow_format_pin_48h', sa.Boolean, nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_column('channel_settings', 'allow_format_post_24h')
    op.drop_column('channel_settings', 'allow_format_post_48h')
    op.drop_column('channel_settings', 'allow_format_post_7d')
    op.drop_column('channel_settings', 'allow_format_pin_24h')
    op.drop_column('channel_settings', 'allow_format_pin_48h')
    # ### end Alembic commands ###
