"""merge_chats_into_telegram_chats

Revision ID: 0ea082555ca4
Revises: 1a2b3c4d5e6f
Create Date: 2026-02-28 05:36:53.213192+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ea082555ca4'
down_revision: str | None = '1a2b3c4d5e6f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chat_type', sa.Enum('channel', 'group', 'supergroup', name='chattype'), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('can_post', sa.Boolean(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('is_scam', sa.Boolean(), nullable=False),
    sa.Column('is_fake', sa.Boolean(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('deactivate_reason', sa.String(length=500), nullable=True),
    sa.Column('last_subscribers', sa.Integer(), nullable=False),
    sa.Column('last_avg_views', sa.Integer(), nullable=False),
    sa.Column('last_er', sa.Float(), nullable=False),
    sa.Column('last_post_frequency', sa.Float(), nullable=False),
    sa.Column('last_parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parse_error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('username')
    )

    # Создаём индексы для mailing-фильтров
    op.create_index('ix_telegram_chats_member_count', 'telegram_chats', ['member_count'])
    op.create_index('ix_telegram_chats_rating', 'telegram_chats', ['rating'])
    op.create_index('ix_telegram_chats_topic_active', 'telegram_chats', ['topic', 'is_active'])
    op.create_index('ix_telegram_chats_is_active', 'telegram_chats', ['is_active'])

    op.create_table('chat_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('subscribers', sa.Integer(), nullable=False),
    sa.Column('subscribers_delta', sa.Integer(), nullable=False),
    sa.Column('subscribers_delta_pct', sa.Float(), nullable=False),
    sa.Column('avg_views', sa.Integer(), nullable=False),
    sa.Column('max_views', sa.Integer(), nullable=False),
    sa.Column('min_views', sa.Integer(), nullable=False),
    sa.Column('posts_analyzed', sa.Integer(), nullable=False),
    sa.Column('er', sa.Float(), nullable=False),
    sa.Column('post_frequency', sa.Float(), nullable=False),
    sa.Column('posts_last_30d', sa.Integer(), nullable=False),
    sa.Column('can_post', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['telegram_chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'snapshot_date', name='uq_chat_snapshot_date'),
    comment='Ежедневные снимки метрик Telegram чатов'
    )

    # Обновляем FK в mailing_logs: chats.id → telegram_chats.id
    op.drop_constraint('mailing_logs_chat_id_fkey', 'mailing_logs', type_='foreignkey')
    op.create_foreign_key(
        'mailing_logs_chat_id_fkey',
        'mailing_logs', 'telegram_chats',
        ['chat_id'], ['id'],
        ondelete='SET NULL'
    )

    # Удаляем старую таблицу chats
    op.drop_table('chats')

    op.alter_column('notifications', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # Восстанавливаем таблицу chats
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_scam', sa.Boolean(), nullable=False),
    sa.Column('is_fake', sa.Boolean(), nullable=False),
    sa.Column('is_broadcast', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_post_reach', sa.Integer(), nullable=True),
    sa.Column('posts_per_day', sa.Float(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('deactivate_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', name='uq_chats_telegram_id')
    )

    # Возвращаем FK в mailing_logs обратно на chats
    op.drop_constraint('mailing_logs_chat_id_fkey', 'mailing_logs', type_='foreignkey')
    op.create_foreign_key(
        'mailing_logs_chat_id_fkey',
        'mailing_logs', 'chats',
        ['chat_id'], ['id'],
        ondelete='SET NULL'
    )

    op.drop_table('chat_snapshots')
    op.drop_table('telegram_chats')
    # ### end Alembic commands ###
