"""add_mailing_status_enum_values

Revision ID: 20260307_120000
Revises: 20260307_100000
Create Date: 2026-03-07 12:00:00.000000+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260307_120000"
down_revision: str | None = "20260307_100000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новые статусы для PENDING_APPROVAL, REJECTED, QUEUED
    # Для PostgreSQL с ENUM type нужно обновить enum

    # Create ENUM type if it doesn't exist (it wasn't created in initial_schema)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE mailingstatus AS ENUM ('pending', 'sending', 'sent', 'failed', 'skipped', 'pending_approval', 'rejected', 'queued');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # Add additional values if needed (PostgreSQL 9.1+)
    op.execute("ALTER TYPE mailingstatus ADD VALUE IF NOT EXISTS 'pending_approval'")
    op.execute("ALTER TYPE mailingstatus ADD VALUE IF NOT EXISTS 'rejected'")
    op.execute("ALTER TYPE mailingstatus ADD VALUE IF NOT EXISTS 'queued'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL не поддерживает удаление ENUM значений без пересоздания таблицы
    # Оставляем как есть для обратой совместимости
    pass
    # ### end Alembic commands ###
