"""add_b2b_package_and_channel_rating_models

Revision ID: 20260307_160000
Revises: 20260307_150000
Create Date: 2026-03-07 16:00:00.000000+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260307_160000"
down_revision: str | None = "20260307_150000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "b2b_packages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("niche", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("channels_count", sa.Integer(), nullable=False),
        sa.Column("guaranteed_reach", sa.Integer(), nullable=False),
        sa.Column("min_er", sa.Float(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount_pct", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("channel_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_b2b_packages_niche", "b2b_packages", ["niche"], unique=False)
    op.create_index("ix_b2b_packages_is_active", "b2b_packages", ["is_active"], unique=False)

    op.create_table(
        "channel_ratings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("subscribers", sa.Integer(), nullable=False),
        sa.Column("avg_views", sa.Integer(), nullable=False),
        sa.Column("er", sa.Float(), nullable=False),
        sa.Column("reach_score", sa.Float(), nullable=False),
        sa.Column("er_score", sa.Float(), nullable=False),
        sa.Column("growth_score", sa.Float(), nullable=False),
        sa.Column("frequency_score", sa.Float(), nullable=False),
        sa.Column("reliability_score", sa.Float(), nullable=False),
        sa.Column("age_score", sa.Float(), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("rank_in_topic", sa.Integer(), nullable=True),
        sa.Column("fraud_flag", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["telegram_chats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", "date", name="uq_channel_rating_date"),
    )
    op.create_index(
        "ix_channel_ratings_channel_id", "channel_ratings", ["channel_id"], unique=False
    )
    op.create_index("ix_channel_ratings_date", "channel_ratings", ["date"], unique=False)
    op.create_index(
        "ix_channel_ratings_total_score", "channel_ratings", ["total_score"], unique=False
    )
    op.create_index(
        "ix_channel_ratings_fraud_flag", "channel_ratings", ["fraud_flag"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_channel_ratings_fraud_flag", table_name="channel_ratings")
    op.drop_index("ix_channel_ratings_total_score", table_name="channel_ratings")
    op.drop_index("ix_channel_ratings_date", table_name="channel_ratings")
    op.drop_index("ix_channel_ratings_channel_id", table_name="channel_ratings")
    op.drop_table("channel_ratings")
    op.drop_index("ix_b2b_packages_is_active", table_name="b2b_packages")
    op.drop_index("ix_b2b_packages_niche", table_name="b2b_packages")
    op.drop_table("b2b_packages")
    # ### end Alembic commands ###
