"""create_platform_account

Revision ID: 013
Revises: 012
Create Date: 2026-03-13

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '013'
down_revision: str | None = '012'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    # Create platform_account table (singleton id=1)
    op.create_table(
        'platform_account',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('escrow_reserved', sa.Numeric(14, 2), nullable=False, server_default='0'),
        sa.Column('payout_reserved', sa.Numeric(14, 2), nullable=False, server_default='0'),
        sa.Column('profit_accumulated', sa.Numeric(14, 2), nullable=False, server_default='0'),
        sa.Column('total_topups', sa.Numeric(14, 2), nullable=False, server_default='0'),
        sa.Column('total_payouts', sa.Numeric(14, 2), nullable=False, server_default='0'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        comment='Системный счёт платформы для аудита балансов',
    )

    # Create singleton record id=1
    op.execute("INSERT INTO platform_account (id) VALUES (1)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_table('platform_account')
    # ### end Alembic commands ###
