"""placement_requests_v42

Revision ID: 015
Revises: 014
Create Date: 2026-03-13

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "015"
down_revision: str | None = "014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    # Create placement_requests table if it doesn't exist (missing from initial schema)
    from alembic import op
    from sqlalchemy import inspect

    conn = op.get_bind()
    inspector = inspect(conn)

    if "placement_requests" not in inspector.get_table_names():
        op.create_table(
            "placement_requests",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("advertiser_id", sa.Integer(), nullable=False),
            sa.Column("campaign_id", sa.Integer(), nullable=False),
            sa.Column("channel_id", sa.Integer(), nullable=False),
            sa.Column("proposed_price", sa.Numeric(10, 2), nullable=False),
            sa.Column("final_price", sa.Numeric(10, 2), nullable=True),
            sa.Column("proposed_schedule", sa.DateTime(timezone=True), nullable=True),
            sa.Column("final_schedule", sa.DateTime(timezone=True), nullable=True),
            sa.Column("proposed_frequency", sa.Integer(), nullable=True),
            sa.Column("final_text", sa.Text(), nullable=False),
            sa.Column("media_file_id", sa.String(512), nullable=True),
            sa.Column(
                "publication_format", sa.String(20), nullable=False, server_default="post_24h"
            ),
            sa.Column("message_id", sa.BigInteger(), nullable=True),
            sa.Column("scheduled_delete_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("status", sa.String(50), nullable=False, server_default="pending_owner"),
            sa.Column("rejection_reason", sa.String(500), nullable=True),
            sa.Column("counter_offer_count", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("last_counter_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("escrow_transaction_id", sa.Integer(), nullable=True),
            sa.Column("meta_json", sa.JSON(), nullable=True),
            sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            ),
            sa.ForeignKeyConstraint(["advertiser_id"], ["users.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["channel_id"], ["telegram_chats.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(
                ["escrow_transaction_id"], ["transactions.id"], ondelete="SET NULL"
            ),
            sa.PrimaryKeyConstraint("id"),
            comment="Заявки на размещение через арбитраж",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_column("placement_requests", "publication_format")
    op.drop_column("placement_requests", "message_id")
    op.drop_column("placement_requests", "scheduled_delete_at")
    op.drop_column("placement_requests", "deleted_at")
    # ### end Alembic commands ###
