"""initial schema

Revision ID: 82cd153da6b8
Revises:
Create Date: 2026-02-22 19:56:43.764355+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "82cd153da6b8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("topic", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_scam", sa.Boolean(), nullable=False),
        sa.Column("is_fake", sa.Boolean(), nullable=False),
        sa.Column("is_broadcast", sa.Boolean(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("last_checked", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("avg_post_reach", sa.Integer(), nullable=True),
        sa.Column("posts_per_day", sa.Float(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("deactivate_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id", name="uq_chats_telegram_id"),
        comment="Telegram чаты для рассылки",
    )
    op.create_index(op.f("ix_chats_is_active"), "chats", ["is_active"], unique=False)
    op.create_index(op.f("ix_chats_last_checked"), "chats", ["last_checked"], unique=False)
    op.create_index(op.f("ix_chats_member_count"), "chats", ["member_count"], unique=False)
    op.create_index("ix_chats_members_active", "chats", ["member_count", "is_active"], unique=False)
    op.create_index("ix_chats_rating_active", "chats", ["rating", "is_active"], unique=False)
    op.create_index(op.f("ix_chats_telegram_id"), "chats", ["telegram_id"], unique=True)
    op.create_index(op.f("ix_chats_topic"), "chats", ["topic"], unique=False)
    op.create_index("ix_chats_topic_active", "chats", ["topic", "is_active"], unique=False)
    op.create_index(op.f("ix_chats_username"), "chats", ["username"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("language_code", sa.String(length=10), nullable=True),
        sa.Column("balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("plan", sa.String(length=50), nullable=False),
        sa.Column("referral_code", sa.String(length=20), nullable=False),
        sa.Column("referred_by_id", sa.BigInteger(), nullable=True),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id", name="uq_users_telegram_id"),
        comment="Пользователи Telegram бота",
    )
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_is_banned"), "users", ["is_banned"], unique=False)
    op.create_index(op.f("ix_users_plan"), "users", ["plan"], unique=False)
    op.create_index(op.f("ix_users_referral_code"), "users", ["referral_code"], unique=True)
    op.create_index(op.f("ix_users_referred_by_id"), "users", ["referred_by_id"], unique=False)
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("ai_description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("filters_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("total_chats", sa.Integer(), nullable=False),
        sa.Column("sent_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="Рекламные кампании пользователей",
    )
    op.create_index(op.f("ix_campaigns_scheduled_at"), "campaigns", ["scheduled_at"], unique=False)
    op.create_index(
        "ix_campaigns_scheduled_status", "campaigns", ["scheduled_at", "status"], unique=False
    )
    op.create_index(op.f("ix_campaigns_status"), "campaigns", ["status"], unique=False)
    op.create_index(op.f("ix_campaigns_user_id"), "campaigns", ["user_id"], unique=False)
    op.create_index("ix_campaigns_user_status", "campaigns", ["user_id", "status"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("payment_id", sa.String(length=255), nullable=True),
        sa.Column("payment_status", sa.String(length=50), nullable=True),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("meta_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("balance_before", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id", name="uq_transactions_payment_id"),
        comment="Финансовые транзакции пользователей",
    )
    op.create_index(
        op.f("ix_transactions_campaign_id"), "transactions", ["campaign_id"], unique=False
    )
    op.create_index("ix_transactions_created", "transactions", ["created_at"], unique=False)
    op.create_index(op.f("ix_transactions_payment_id"), "transactions", ["payment_id"], unique=True)
    op.create_index(
        op.f("ix_transactions_processed_at"), "transactions", ["processed_at"], unique=False
    )
    op.create_index(op.f("ix_transactions_type"), "transactions", ["type"], unique=False)
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    op.create_index("ix_transactions_user_type", "transactions", ["user_id", "type"], unique=False)
    op.create_table(
        "content_flags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("categories", sa.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("flagged_fragments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("decision", sa.String(length=50), nullable=False),
        sa.Column("reviewed_by_id", sa.Integer(), nullable=True),
        sa.Column("review_comment", sa.Text(), nullable=True),
        sa.Column("filter_score", sa.Float(), nullable=False),
        sa.Column("llm_analysis", sa.Text(), nullable=True),
        sa.Column("llm_categories", sa.ARRAY(sa.String(length=50)), nullable=True),
        sa.Column("auto_checked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", name="uq_content_flags_campaign_id"),
        comment="Флаги модерации контента",
    )
    op.create_index(
        op.f("ix_content_flags_campaign_id"), "content_flags", ["campaign_id"], unique=True
    )
    op.create_index(
        "ix_content_flags_categories",
        "content_flags",
        ["categories"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_content_flags_decision"), "content_flags", ["decision"], unique=False)
    op.create_index(
        op.f("ix_content_flags_reviewed_by_id"), "content_flags", ["reviewed_by_id"], unique=False
    )
    op.create_table(
        "mailing_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("chat_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "campaign_id", "chat_telegram_id", name="uq_mailing_logs_campaign_chat"
        ),
        comment="Логи рассылок по кампаниям",
    )
    op.create_index(
        op.f("ix_mailing_logs_campaign_id"), "mailing_logs", ["campaign_id"], unique=False
    )
    op.create_index(op.f("ix_mailing_logs_chat_id"), "mailing_logs", ["chat_id"], unique=False)
    op.create_index(
        "ix_mailing_logs_chat_telegram", "mailing_logs", ["chat_telegram_id"], unique=False
    )
    op.create_index(
        op.f("ix_mailing_logs_chat_telegram_id"), "mailing_logs", ["chat_telegram_id"], unique=False
    )
    op.create_index(op.f("ix_mailing_logs_sent_at"), "mailing_logs", ["sent_at"], unique=False)
    op.create_index(op.f("ix_mailing_logs_status"), "mailing_logs", ["status"], unique=False)
    op.create_index(
        "ix_mailing_logs_status_campaign", "mailing_logs", ["status", "campaign_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mailing_logs_status_campaign", table_name="mailing_logs")
    op.drop_index(op.f("ix_mailing_logs_status"), table_name="mailing_logs")
    op.drop_index(op.f("ix_mailing_logs_sent_at"), table_name="mailing_logs")
    op.drop_index(op.f("ix_mailing_logs_chat_telegram_id"), table_name="mailing_logs")
    op.drop_index("ix_mailing_logs_chat_telegram", table_name="mailing_logs")
    op.drop_index(op.f("ix_mailing_logs_chat_id"), table_name="mailing_logs")
    op.drop_index(op.f("ix_mailing_logs_campaign_id"), table_name="mailing_logs")
    op.drop_table("mailing_logs")
    op.drop_index(op.f("ix_content_flags_reviewed_by_id"), table_name="content_flags")
    op.drop_index(op.f("ix_content_flags_decision"), table_name="content_flags")
    op.drop_index("ix_content_flags_categories", table_name="content_flags", postgresql_using="gin")
    op.drop_index(op.f("ix_content_flags_campaign_id"), table_name="content_flags")
    op.drop_table("content_flags")
    op.drop_index("ix_transactions_user_type", table_name="transactions")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_type"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_processed_at"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_payment_id"), table_name="transactions")
    op.drop_index("ix_transactions_created", table_name="transactions")
    op.drop_index(op.f("ix_transactions_campaign_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("ix_campaigns_user_status", table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_user_id"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_status"), table_name="campaigns")
    op.drop_index("ix_campaigns_scheduled_status", table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_scheduled_at"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_index(op.f("ix_users_referred_by_id"), table_name="users")
    op.drop_index(op.f("ix_users_referral_code"), table_name="users")
    op.drop_index(op.f("ix_users_plan"), table_name="users")
    op.drop_index(op.f("ix_users_is_banned"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_chats_username"), table_name="chats")
    op.drop_index("ix_chats_topic_active", table_name="chats")
    op.drop_index(op.f("ix_chats_topic"), table_name="chats")
    op.drop_index(op.f("ix_chats_telegram_id"), table_name="chats")
    op.drop_index("ix_chats_rating_active", table_name="chats")
    op.drop_index("ix_chats_members_active", table_name="chats")
    op.drop_index(op.f("ix_chats_member_count"), table_name="chats")
    op.drop_index(op.f("ix_chats_last_checked"), table_name="chats")
    op.drop_index(op.f("ix_chats_is_active"), table_name="chats")
    op.drop_table("chats")
    # ### end Alembic commands ###
