"""initial_schema_v4_3

Revision ID: a86e3ba47c30
Revises:
Create Date: 2026-03-14 21:14:59.257053

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a86e3ba47c30'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name_ru', sa.String(length=128), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('platform_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escrow_reserved', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('payout_reserved', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('profit_accumulated', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_topups', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_payouts', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('current_role', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('plan', sa.String(length=16), server_default='free', nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('balance_rub', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('earned_rub', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('credits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('referral_code', sa.String(length=32), nullable=False),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('advertiser_xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('advertiser_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('owner_xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('owner_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('ai_uses_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ai_uses_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('payout_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'paid', 'rejected', 'cancelled', name='payoutstatus'), nullable=False),
    sa.Column('requisites', sa.String(length=512), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_requests_owner_id'), 'payout_requests', ['owner_id'], unique=False)
    op.create_index(op.f('ix_payout_requests_status'), 'payout_requests', ['status'], unique=False)
    op.create_table('reputation_scores',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('advertiser_score', sa.Float(), server_default='5.0', nullable=False),
    sa.Column('owner_score', sa.Float(), server_default='5.0', nullable=False),
    sa.Column('is_advertiser_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_owner_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('advertiser_blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('advertiser_violations_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('owner_violations_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('telegram_chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('member_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_er', sa.Float(), server_default='0', nullable=False),
    sa.Column('avg_views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating', sa.Float(), server_default='0', nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_parsed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_telegram_chats_category'), 'telegram_chats', ['category'], unique=False)
    op.create_index(op.f('ix_telegram_chats_owner_id'), 'telegram_chats', ['owner_id'], unique=False)
    op.create_index(op.f('ix_telegram_chats_telegram_id'), 'telegram_chats', ['telegram_id'], unique=True)
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_type', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('yookassa_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('desired_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('payment_url', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yookassa_payments_payment_id'), 'yookassa_payments', ['payment_id'], unique=True)
    op.create_index(op.f('ix_yookassa_payments_user_id'), 'yookassa_payments', ['user_id'], unique=False)
    op.create_table('channel_mediakits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audience_description', sa.Text(), nullable=True),
    sa.Column('avg_post_reach', sa.Integer(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('downloads_count', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['telegram_chats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('channel_settings',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('price_per_post', sa.Numeric(precision=10, scale=2), server_default='1000', nullable=False),
    sa.Column('allow_format_post_24h', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('allow_format_post_48h', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('allow_format_post_7d', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_format_pin_24h', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_format_pin_48h', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('max_posts_per_day', sa.Integer(), server_default='2', nullable=False),
    sa.Column('max_posts_per_week', sa.Integer(), server_default='10', nullable=False),
    sa.Column('publish_start_time', sa.Time(), nullable=False),
    sa.Column('publish_end_time', sa.Time(), nullable=False),
    sa.Column('break_start_time', sa.Time(), nullable=True),
    sa.Column('break_end_time', sa.Time(), nullable=True),
    sa.Column('auto_accept_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['telegram_chats.id'], ),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('placement_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending_owner', 'counter_offer', 'pending_payment', 'escrow', 'published', 'failed', 'failed_permissions', 'refunded', 'cancelled', name='placementstatus'), nullable=False),
    sa.Column('publication_format', sa.Enum('post_24h', 'post_48h', 'post_7d', 'pin_24h', 'pin_48h', name='publicationformat'), nullable=False),
    sa.Column('ad_text', sa.Text(), nullable=False),
    sa.Column('proposed_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proposed_schedule', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_schedule', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counter_offer_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('counter_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('counter_schedule', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counter_comment', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_reach', sa.Integer(), nullable=True),
    sa.Column('clicks_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tracking_short_code', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['telegram_chats.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_short_code')
    )
    op.create_index(op.f('ix_placement_requests_advertiser_id'), 'placement_requests', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_placement_requests_channel_id'), 'placement_requests', ['channel_id'], unique=False)
    op.create_index(op.f('ix_placement_requests_expires_at'), 'placement_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_placement_requests_owner_id'), 'placement_requests', ['owner_id'], unique=False)
    op.create_index(op.f('ix_placement_requests_scheduled_delete_at'), 'placement_requests', ['scheduled_delete_at'], unique=False)
    op.create_index(op.f('ix_placement_requests_status'), 'placement_requests', ['status'], unique=False)
    op.create_index('ix_placement_requests_status_expires', 'placement_requests', ['status', 'expires_at'], unique=False)
    op.create_table('placement_disputes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placement_request_id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('post_removed_early', 'bot_kicked', 'advertiser_complaint', name='disputereason'), nullable=False),
    sa.Column('status', sa.Enum('open', 'owner_explained', 'resolved', name='disputestatus'), nullable=False),
    sa.Column('owner_explanation', sa.Text(), nullable=True),
    sa.Column('advertiser_comment', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Enum('owner_fault', 'advertiser_fault', 'technical', 'partial', name='disputeresolution'), nullable=True),
    sa.Column('resolution_comment', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('advertiser_refund_pct', sa.Float(), nullable=True),
    sa.Column('owner_payout_pct', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['advertiser_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['placement_request_id'], ['placement_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_disputes_placement_request_id'), 'placement_disputes', ['placement_request_id'], unique=False)
    op.create_index(op.f('ix_placement_disputes_status'), 'placement_disputes', ['status'], unique=False)
    op.create_table('reputation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('action', sa.Enum('publication', 'review_5star', 'review_4star', 'review_3star', 'review_2star', 'review_1star', 'cancel_before_escrow', 'cancel_after_confirm', 'cancel_systematic', 'reject_invalid_1', 'reject_invalid_2', 'reject_invalid_3', 'reject_frequent', 'dispute_owner_fault', 'recovery_30days', 'ban_reset', name='reputationaction'), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('score_before', sa.Float(), nullable=False),
    sa.Column('score_after', sa.Float(), nullable=False),
    sa.Column('placement_request_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['placement_request_id'], ['placement_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_history_user_id'), 'reputation_history', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placement_request_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['placement_request_id'], ['placement_requests.id'], ),
    sa.ForeignKeyConstraint(['reviewed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placement_request_id')
    )
    op.create_index(op.f('ix_reviews_reviewed_id'), 'reviews', ['reviewed_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('topup', 'escrow_freeze', 'escrow_release', 'platform_fee', 'refund_full', 'refund_partial', 'cancel_penalty', 'owner_cancel_compensation', 'payout', 'payout_fee', 'credits_buy', 'failed_permissions_refund', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('placement_request_id', sa.Integer(), nullable=True),
    sa.Column('payout_id', sa.Integer(), nullable=True),
    sa.Column('yookassa_payment_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payout_id'], ['payout_requests.id'], ),
    sa.ForeignKeyConstraint(['placement_request_id'], ['placement_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_placement_request_id'), 'transactions', ['placement_request_id'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_placement_request_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewed_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reputation_history_user_id'), table_name='reputation_history')
    op.drop_table('reputation_history')
    op.drop_index(op.f('ix_placement_disputes_status'), table_name='placement_disputes')
    op.drop_index(op.f('ix_placement_disputes_placement_request_id'), table_name='placement_disputes')
    op.drop_table('placement_disputes')
    op.drop_index('ix_placement_requests_status_expires', table_name='placement_requests')
    op.drop_index(op.f('ix_placement_requests_status'), table_name='placement_requests')
    op.drop_index(op.f('ix_placement_requests_scheduled_delete_at'), table_name='placement_requests')
    op.drop_index(op.f('ix_placement_requests_owner_id'), table_name='placement_requests')
    op.drop_index(op.f('ix_placement_requests_expires_at'), table_name='placement_requests')
    op.drop_index(op.f('ix_placement_requests_channel_id'), table_name='placement_requests')
    op.drop_index(op.f('ix_placement_requests_advertiser_id'), table_name='placement_requests')
    op.drop_table('placement_requests')
    op.drop_table('channel_settings')
    op.drop_table('channel_mediakits')
    op.drop_index(op.f('ix_yookassa_payments_user_id'), table_name='yookassa_payments')
    op.drop_index(op.f('ix_yookassa_payments_payment_id'), table_name='yookassa_payments')
    op.drop_table('yookassa_payments')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_telegram_chats_telegram_id'), table_name='telegram_chats')
    op.drop_index(op.f('ix_telegram_chats_owner_id'), table_name='telegram_chats')
    op.drop_index(op.f('ix_telegram_chats_category'), table_name='telegram_chats')
    op.drop_table('telegram_chats')
    op.drop_table('reputation_scores')
    op.drop_index(op.f('ix_payout_requests_status'), table_name='payout_requests')
    op.drop_index(op.f('ix_payout_requests_owner_id'), table_name='payout_requests')
    op.drop_table('payout_requests')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('platform_account')
    op.drop_table('categories')
    # ### end Alembic commands ###
