"""
Константы приложения Market Bot.

Централизованное хранилище всех констант проекта для упрощения поддержки.
"""

from .ai import (
    AI_MAX_TOKENS,
    AI_MODEL,
    AI_TEMPERATURE,
    BUSINESS_AI_GENERATIONS_LIMIT,
    DEFAULT_SYSTEM_PROMPT,
    FREE_AI_GENERATIONS_LIMIT,
    PRO_AI_GENERATIONS_LIMIT,
    STARTER_AI_GENERATIONS_LIMIT,
)
from .content_filter import (
    BLOCKED_CATEGORIES,
    LEVEL1_THRESHOLD,
    LEVEL2_THRESHOLD,
    LEVEL3_THRESHOLD,
)
from .parser import (
    PARSER_POSTS_SAMPLE,
    PARSER_RATE_LIMIT_DELAY,
    POPULAR_TOPICS,
    SEARCH_QUERIES,
    SEARCH_QUERIES_BY_CATEGORY,
)
from .payments import (
    FORMAT_DURATIONS_SECONDS,
    FORMAT_MULTIPLIERS,
    MAX_TOPUP,
    MIN_CAMPAIGN_BUDGET,
    MIN_PAYOUT,
    MIN_PRICE_PER_POST,
    MIN_TOPUP,
    OWNER_SHARE,
    PLAN_LIMITS,
    PLAN_PRICES,
    PLATFORM_COMMISSION,
    QUICK_TOPUP_AMOUNTS,
)
from .tariffs import (
    PREMIUM_SUBSCRIBER_THRESHOLD,
    TARIFF_LABELS,
    TARIFF_MIN_RATING,
    TARIFF_SUBSCRIBER_LIMITS,
    TARIFF_TOPICS,
)

__all__ = [
    # AI
    "AI_MODEL",
    "AI_MAX_TOKENS",
    "AI_TEMPERATURE",
    "FREE_AI_GENERATIONS_LIMIT",
    "STARTER_AI_GENERATIONS_LIMIT",
    "PRO_AI_GENERATIONS_LIMIT",
    "BUSINESS_AI_GENERATIONS_LIMIT",
    "DEFAULT_SYSTEM_PROMPT",
    # Tariffs
    "TARIFF_LABELS",
    "TARIFF_SUBSCRIBER_LIMITS",
    "TARIFF_MIN_RATING",
    "TARIFF_TOPICS",
    "PREMIUM_SUBSCRIBER_THRESHOLD",
    # Payments
    "PLATFORM_COMMISSION",
    "OWNER_SHARE",
    "PLAN_PRICES",
    "PLAN_LIMITS",
    "MIN_TOPUP",
    "MAX_TOPUP",
    "MIN_CAMPAIGN_BUDGET",
    "MIN_PRICE_PER_POST",
    "MIN_PAYOUT",
    "QUICK_TOPUP_AMOUNTS",
    "FORMAT_MULTIPLIERS",
    "FORMAT_DURATIONS_SECONDS",
    # Parser
    "SEARCH_QUERIES",
    "SEARCH_QUERIES_BY_CATEGORY",
    "PARSER_POSTS_SAMPLE",
    "PARSER_RATE_LIMIT_DELAY",
    "POPULAR_TOPICS",
    # Content filter
    "LEVEL1_THRESHOLD",
    "LEVEL2_THRESHOLD",
    "LEVEL3_THRESHOLD",
    "BLOCKED_CATEGORIES",
]
