"""
Константы приложения Market Bot.

Централизованное хранилище всех констант проекта для упрощения поддержки.
"""

from .ai import (
    AI_MAX_TOKENS,
    AI_TEMPERATURE,
    BUSINESS_AI_GENERATIONS_LIMIT,
    DEFAULT_SYSTEM_PROMPT,
    FALLBACK_MODEL,
    FREE_AI_GENERATIONS_LIMIT,
    FREE_MODEL,
    PAID_MODEL,
    PRO_AI_GENERATIONS_LIMIT,
    STARTER_AI_GENERATIONS_LIMIT,
)
from .content_filter import (
    BLOCKED_CATEGORIES,
    LEVEL1_THRESHOLD,
    LEVEL2_THRESHOLD,
    LEVEL3_THRESHOLD,
)
from .parser import (
    PARSER_POSTS_SAMPLE,
    PARSER_RATE_LIMIT_DELAY,
    POPULAR_TOPICS,
    SEARCH_QUERIES,
    SEARCH_QUERIES_BY_CATEGORY,
)
from .payments import (
    CREDIT_PACKAGE_BUSINESS,
    CREDIT_PACKAGE_STANDARD,
    CREDIT_PACKAGES,
    CRYPTO_CURRENCIES,
    CURRENCIES,
    PAYMENT_METHODS,
)
from .tariffs import (
    PREMIUM_SUBSCRIBER_THRESHOLD,
    TARIFF_CREDIT_COST,
    TARIFF_LABELS,
    TARIFF_MIN_RATING,
    TARIFF_SUBSCRIBER_LIMITS,
    TARIFF_TOPICS,
)

__all__ = [
    # AI
    "FREE_MODEL",
    "FALLBACK_MODEL",
    "PAID_MODEL",
    "AI_MAX_TOKENS",
    "AI_TEMPERATURE",
    "FREE_AI_GENERATIONS_LIMIT",
    "STARTER_AI_GENERATIONS_LIMIT",
    "PRO_AI_GENERATIONS_LIMIT",
    "BUSINESS_AI_GENERATIONS_LIMIT",
    "DEFAULT_SYSTEM_PROMPT",
    # Tariffs
    "TARIFF_CREDIT_COST",
    "TARIFF_LABELS",
    "TARIFF_SUBSCRIBER_LIMITS",
    "TARIFF_MIN_RATING",
    "TARIFF_TOPICS",
    "PREMIUM_SUBSCRIBER_THRESHOLD",
    # Payments
    "CREDIT_PACKAGES",
    "CREDIT_PACKAGE_STANDARD",
    "CREDIT_PACKAGE_BUSINESS",
    "CURRENCIES",
    "CRYPTO_CURRENCIES",
    "PAYMENT_METHODS",
    # Parser
    "SEARCH_QUERIES",
    "SEARCH_QUERIES_BY_CATEGORY",
    "PARSER_POSTS_SAMPLE",
    "PARSER_RATE_LIMIT_DELAY",
    "POPULAR_TOPICS",
    # Content filter
    "LEVEL1_THRESHOLD",
    "LEVEL2_THRESHOLD",
    "LEVEL3_THRESHOLD",
    "BLOCKED_CATEGORIES",
]
