"""
Константы парсера Telegram каналов.
"""

# Строковые константы для часто повторяющихся тематических меток
TOPIC_BIZNES = "бизнес"
TOPIC_MARKETING = "маркетинг"
TOPIC_PRODAZHI = "продажи"
TOPIC_TRADING = "трейдинг"
TOPIC_INVESTITSII = "инвестиции"
TOPIC_KRIPTOVALYUTA = "криптовалюта"
TOPIC_PSIKHOLOGIYA = "психология"
TOPIC_OTNOSHENIYA = "отношения"
TOPIC_ZDOROVYE = "здоровье"
TOPIC_PUTESHESTVIYA = "путешествия"
TOPIC_KRASOTA = "красота"
TOPIC_PROGRAMMIROVANIE = "программирование"
TOPIC_FINANSY = "финансы"
TOPIC_BIZNES_NOVOSTI = "бизнес новости"
TOPIC_BITCOIN = "биткоин"
TOPIC_SMM = "smm"
TOPIC_MODA = "мода"
TOPIC_KINO = "кино"
TOPIC_IT = "it"
TOPIC_ETHEREUM = "ethereum"
TOPIC_EDA = "еда"
TOPIC_YUMOR = "юмор"
TOPIC_DEFI = "defi"
TOPIC_NFT = "nft"

# Количество постов для анализа каждого канала
PARSER_POSTS_SAMPLE: int = 50

# Задержка между запросами (rate limiting, секунды)
PARSER_RATE_LIMIT_DELAY: float = 0.5

# Популярные тематики для поиска каналов
POPULAR_TOPICS: list[str] = [
    TOPIC_BIZNES,
    TOPIC_MARKETING,
    TOPIC_PRODAZHI,
    TOPIC_TRADING,
    TOPIC_INVESTITSII,
    TOPIC_KRIPTOVALYUTA,
    "недвижимость",
    TOPIC_PSIKHOLOGIYA,
    TOPIC_OTNOSHENIYA,
    TOPIC_ZDOROVYE,
    "спорт",
    TOPIC_PUTESHESTVIYA,
    TOPIC_EDA,
    TOPIC_MODA,
    TOPIC_KRASOTA,
    TOPIC_YUMOR,
    "новости",
    "политика",
    "технологии",
    TOPIC_IT,
    TOPIC_PROGRAMMIROVANIE,
    "стартапы",
    "карьера",
    "образование",
    "наука",
    "искусство",
    "дизайн",
    "фотография",
    TOPIC_KINO,
    "музыка",
    "книги",
    "игры",
    "авто",
    TOPIC_FINANSY,
    "блогеры",
    "медиа",
    "реклама",
    TOPIC_SMM,
]

# Поисковые запросы для парсинга Telegram (расширенный список ~250 запросов)
# Разбит по тематикам для равномерного распределения нагрузки
SEARCH_QUERIES: list[str] = [
    # Бизнес и финансы (35)
    TOPIC_BIZNES,
    TOPIC_BIZNES_NOVOSTI,
    "бизнес идеи",
    "стартап",
    "стартапы россия",
    TOPIC_INVESTITSII,
    "инвестиции для начинающих",
    "фондовый рынок",
    TOPIC_TRADING,
    "крипта",
    TOPIC_KRIPTOVALYUTA,
    TOPIC_BITCOIN,
    TOPIC_ETHEREUM,
    TOPIC_DEFI,
    TOPIC_NFT,
    TOPIC_FINANSY,
    "финансовая грамотность",
    "деньги",
    "заработок",
    "пассивный доход",
    "предпринимательство",
    "малый бизнес",
    "ип",
    "самозанятый",
    "бизнес молодость",
    "трансформатор",
    "радашевски",
    "слишко",
    "академия трейдинга",
    "школа инвестиций",
    "управление бизнесом",
    "корпоративное управление",
    "стратегия бизнеса",
    "масштабирование бизнеса",
    "франшиза бизнес",
    # Маркетинг и продажи (30)
    TOPIC_MARKETING,
    "digital маркетинг",
    TOPIC_SMM,
    "таргетинг",
    "контекстная реклама",
    TOPIC_PRODAZHI,
    "продажи b2b",
    "продажи b2c",
    "переговоры",
    "клиенты",
    "бренд",
    "pr",
    "контент маркетинг",
    "email маркетинг",
    "лидогенерация",
    "воронка продаж",
    "crm система",
    "скрипты продаж",
    "холодные звонки",
    "менеджеры по продажам",
    "маркетологи",
    "директолог",
    "таргетолог",
    "smm специалист",
    "продвижение telegram",
    "telegram каналы",
    "telegram маркетинг",
    "telegram боты",
    "чат боты",
    "автоворонки",
    # IT и технологии (30)
    TOPIC_IT,
    "айти",
    TOPIC_PROGRAMMIROVANIE,
    "разработка",
    "веб разработка",
    "frontend",
    "backend",
    "fullstack",
    "python",
    "javascript",
    "typescript",
    "react",
    "vue",
    "angular",
    "nodejs",
    "django",
    "fastapi",
    "flask",
    "golang",
    "java",
    "c++",
    "rust",
    "php",
    "laravel",
    "symfony",
    "mobile development",
    "ios разработка",
    "android разработка",
    "flutter",
    "react native",
    "swift",
    "kotlin",
    # Криптовалюты и блокчейн (25)
    TOPIC_KRIPTOVALYUTA,
    "крипта",
    TOPIC_BITCOIN,
    "bitcoin",
    TOPIC_ETHEREUM,
    "eth",
    "altcoins",
    "altcoins gems",
    TOPIC_DEFI,
    TOPIC_NFT,
    "nft коллекция",
    "блокчейн",
    "blockchain",
    "binance",
    "bybit",
    "okx",
    "huobi",
    "криптобиржа",
    "трейдинг криптовалют",
    "крипто сигналы",
    "крипто аналитика",
    "web3",
    "metaverse",
    "dao",
    "staking",
    # Психология и отношения (25)
    TOPIC_PSIKHOLOGIYA,
    "психолог",
    "психология отношений",
    "семейная психология",
    "детская психология",
    "самооценка",
    "уверенность в себе",
    "мотивация",
    "саморазвитие",
    "личностный рост",
    "медитация",
    "осознанность",
    " mindfulness",
    "эмоциональный интеллект",
    "стресс",
    "тревожность",
    "депрессия",
    "терапия",
    "коучинг",
    "лайф коуч",
    "бизнес коуч",
    TOPIC_OTNOSHENIYA,
    "мужчина женщина",
    "свидания",
    "знакомства",
    # Здоровье и спорт (25)
    TOPIC_ZDOROVYE,
    "зож",
    "правильное питание",
    "пп рецепты",
    "диеты",
    "похудение",
    "набор массы",
    "фитнес",
    "тренировки",
    "спортзал",
    "бег",
    "йога",
    "пилатес",
    "кроссфит",
    "бодибилдинг",
    "пауэрлифтинг",
    "единоборства",
    "бокс",
    "mma",
    "футбол",
    "хоккей",
    "баскетбол",
    "теннис",
    "гольф",
    "велоспорт",
    # Путешествия и туризм (20)
    TOPIC_PUTESHESTVIYA,
    "туризм",
    "отпуск",
    "каникулы",
    "туры",
    "авиабилеты",
    "отели",
    "хостелы",
    "европа",
    "азия",
    "таиланд",
    "турция",
    "египет",
    "оаэ",
    "мальдивы",
    "бали",
    "вьетнам",
    "китай",
    "япония",
    "корей",
    # Еда и рестораны (15)
    TOPIC_EDA,
    "рестораны",
    "кафе",
    "бары",
    "кулинария",
    "рецепты",
    "выпечка",
    "десерты",
    "торты",
    "пицца",
    "суши",
    "бургеры",
    "кофе",
    "вино",
    "коктейли",
    # Мода и красота (20)
    TOPIC_MODA,
    "стиль",
    "имидж",
    "шоппинг",
    "бренды одежды",
    "дизайнеры",
    "показы мод",
    TOPIC_KRASOTA,
    "косметика",
    "макияж",
    "уход за кожей",
    "skincare",
    "маникюр",
    "педикюр",
    "прически",
    "стрижки",
    "окрашивание",
    "парикмахер",
    "визажист",
    "стилист",
    # Юмор и развлечения (15)
    TOPIC_YUMOR,
    "приколы",
    "мемы",
    "комедии",
    "стендап",
    "квн",
    "развлечения",
    "шоу",
    "сериалы",
    "фильмы",
    TOPIC_KINO,
    "актеры",
    "режиссеры",
    "премьеры",
    "кинокритик",
    # Новости и медиа (15)
    "новости",
    " сми",
    "тв",
    "телевидение",
    "радио",
    "подкасты",
    "журналистика",
    "политика",
    "экономика",
    "общество",
    "происшествия",
    "спорт новости",
    TOPIC_BIZNES_NOVOSTI,
    "технологии новости",
    "наука новости",
]

# Поисковые запросы по категориям (для структурированного парсинга)
SEARCH_QUERIES_BY_CATEGORY: dict[str, list[str]] = {
    "business": [
        TOPIC_BIZNES,
        TOPIC_BIZNES_NOVOSTI,
        "бизнес идеи",
        "стартап",
        TOPIC_INVESTITSII,
        TOPIC_FINANSY,
        "деньги",
        "заработок",
        "предпринимательство",
        "малый бизнес",
    ],
    "marketing": [
        TOPIC_MARKETING,
        "digital маркетинг",
        TOPIC_SMM,
        "таргетинг",
        TOPIC_PRODAZHI,
        "реклама",
        "бренд",
        "pr",
        "контент маркетинг",
        "лидогенерация",
    ],
    "it": [
        TOPIC_IT,
        TOPIC_PROGRAMMIROVANIE,
        "разработка",
        "python",
        "javascript",
        "веб разработка",
        "mobile development",
        "frontend",
        "backend",
        "golang",
    ],
    "crypto": [
        TOPIC_KRIPTOVALYUTA,
        TOPIC_BITCOIN,
        TOPIC_ETHEREUM,
        TOPIC_DEFI,
        TOPIC_NFT,
        "блокчейн",
        TOPIC_TRADING,
        "криптобиржа",
        "web3",
        "staking",
    ],
    "psychology": [
        TOPIC_PSIKHOLOGIYA,
        TOPIC_OTNOSHENIYA,
        "самооценка",
        "мотивация",
        "саморазвитие",
        "медитация",
        "коучинг",
        "терапия",
        "эмоциональный интеллект",
        "стресс",
    ],
    "health": [
        TOPIC_ZDOROVYE,
        "зож",
        "фитнес",
        "тренировки",
        "питание",
        "диеты",
        "похудение",
        "йога",
        "бег",
        "спорт",
    ],
    "travel": [
        TOPIC_PUTESHESTVIYA,
        "туризм",
        "отпуск",
        "туры",
        "авиабилеты",
        "отели",
        "европа",
        "азия",
        "таиланд",
        "бали",
    ],
    "food": [
        TOPIC_EDA,
        "рестораны",
        "кулинария",
        "рецепты",
        "выпечка",
        "десерты",
        "кофе",
        "вино",
        "коктейли",
        "пп рецепты",
    ],
    "fashion": [
        TOPIC_MODA,
        "стиль",
        "шоппинг",
        "бренды",
        "дизайнеры",
        TOPIC_KRASOTA,
        "косметика",
        "макияж",
        "skincare",
        "прически",
    ],
    "entertainment": [
        TOPIC_YUMOR,
        "приколы",
        "мемы",
        TOPIC_KINO,
        "сериалы",
        "фильмы",
        "музыка",
        "шоу",
        "развлечения",
        "стендап",
    ],
}
