"""Initial schema - create all tables

Revision ID: 0015
Revises: 0014
Create Date: 2026-03-10

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust by ###
    # This is the initial migration after audit
    # Add check constraints and indexes identified during audit
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust by ###
    pass
    # ### end Alembic commands ###
