"""add_mailing_log_meta_json

Revision ID: 9de36b5c6cd5
Revises: ca10fe276562
Create Date: 2026-03-09 20:29:52.864687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9de36b5c6cd5'
down_revision: Union[str, None] = 'ca10fe276562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailing_logs', sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailing_logs', 'meta_json')
    # ### end Alembic commands ###
