"""Add scheduled_at and rejection_reason to mailing_logs, add CHANGES_REQUESTED to MailingStatus

Revision ID: ca10fe276562
Revises: 370fc109237f
Create Date: 2026-03-09 21:20:18.625884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca10fe276562'
down_revision: Union[str, None] = '370fc109237f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_categories_is_active'), table_name='topic_categories')
    op.drop_index(op.f('ix_topic_categories_subcategory'), table_name='topic_categories')
    op.drop_index(op.f('ix_topic_categories_topic'), table_name='topic_categories')
    op.drop_table('topic_categories')
    op.alter_column('b2b_packages', 'channel_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('b2b_packages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('b2b_packages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_table_comment(
        'b2b_packages',
        'Пакетные предложения B2B-маркетплейса',
        existing_comment=None,
        schema=None
    )
    op.alter_column('badge_achievements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('badge_achievements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_badge_achievements_active'), table_name='badge_achievements')
    op.drop_index(op.f('ix_badge_achievements_type'), table_name='badge_achievements')
    op.create_index(op.f('ix_badge_achievements_achievement_type'), 'badge_achievements', ['achievement_type'], unique=False)
    op.create_index(op.f('ix_badge_achievements_badge_id'), 'badge_achievements', ['badge_id'], unique=False)
    op.create_index(op.f('ix_badge_achievements_is_active'), 'badge_achievements', ['is_active'], unique=False)
    op.create_table_comment(
        'badge_achievements',
        'Шаблоны достижений для автоматической выдачи значков',
        existing_comment=None,
        schema=None
    )
    op.alter_column('badges', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('badges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_table_comment(
        'badges',
        'Каталог значков платформы',
        existing_comment=None,
        schema=None
    )
    op.alter_column('channel_mediakits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('channel_mediakits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_channel_mediakits_owner_id'), table_name='channel_mediakits')
    op.create_index(op.f('ix_channel_mediakits_owner_user_id'), 'channel_mediakits', ['owner_user_id'], unique=False)
    op.create_table_comment(
        'channel_mediakits',
        'Медиакиты каналов для привлечения рекламодателей',
        existing_comment=None,
        schema=None
    )
    op.alter_column('channel_ratings', 'channel_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('channel_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('channel_ratings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_table_comment(
        'channel_ratings',
        'Ежедневные рейтинги каналов',
        existing_comment=None,
        schema=None
    )
    op.add_column('mailing_logs', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.alter_column('mailing_logs', 'rejection_reason',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Причина отклонения заявки',
               existing_nullable=True)
    op.drop_column('mailing_logs', 'auto_approve_notified')
    op.alter_column('payouts', 'owner_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('payouts', 'channel_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('payouts', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('payouts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('payouts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_payouts_placement_id'), table_name='payouts')
    op.create_index(op.f('ix_payouts_placement_id'), 'payouts', ['placement_id'], unique=False)
    op.create_table_comment(
        'payouts',
        'Выплаты владельцам каналов за рекламные размещения',
        existing_comment=None,
        schema=None
    )
    op.alter_column('reviews', 'reviewer_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('reviews', 'reviewee_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('reviews', 'channel_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_table_comment(
        'reviews',
        'Отзывы о размещениях (двусторонняя оценка)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('telegram_chats', 'last_classified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Когда последний раз была LLM-классификация',
               existing_nullable=True)
    op.alter_column('telegram_chats', 'llm_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Уверенность LLM при последней классификации (0.0–1.0)',
               existing_nullable=True)
    op.alter_column('telegram_chats', 'recent_posts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Последние 5 постов для LLM-классификации (см. RecentPostJSON)',
               existing_nullable=True)
    op.alter_column('telegram_chats', 'bot_is_admin',
               existing_type=sa.BOOLEAN(),
               comment='Бот добавлен администратором в канале',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('telegram_chats', 'admin_added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Когда бот был добавлен администратором',
               existing_nullable=True)
    op.alter_column('telegram_chats', 'owner_user_id',
               existing_type=sa.BIGINT(),
               comment='Владелец канала (FK на users.id)',
               existing_nullable=True)
    op.alter_column('telegram_chats', 'price_per_post',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Цена за один рекламный пост в рублях',
               existing_nullable=True)
    op.alter_column('telegram_chats', 'is_accepting_ads',
               existing_type=sa.BOOLEAN(),
               comment='Канал принимает рекламные размещения',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_badges', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_badges', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('user_badges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_table_comment(
        'user_badges',
        'Выданные значки пользователей',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users', 'advertiser_xp',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='XP рекламодателя (за запуск кампаний)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'owner_xp',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='XP владельца (за публикации в канале)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'advertiser_level',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уровень рекламодателя',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'owner_level',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уровень владельца канала',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_users_advertiser_level'), table_name='users')
    op.drop_index(op.f('ix_users_advertiser_xp'), table_name='users')
    op.drop_index(op.f('ix_users_last_login_at'), table_name='users')
    op.drop_index(op.f('ix_users_owner_level'), table_name='users')
    op.drop_index(op.f('ix_users_owner_xp'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_owner_xp'), 'users', ['owner_xp'], unique=False)
    op.create_index(op.f('ix_users_owner_level'), 'users', ['owner_level'], unique=False)
    op.create_index(op.f('ix_users_last_login_at'), 'users', ['last_login_at'], unique=False)
    op.create_index(op.f('ix_users_advertiser_xp'), 'users', ['advertiser_xp'], unique=False)
    op.create_index(op.f('ix_users_advertiser_level'), 'users', ['advertiser_level'], unique=False)
    op.alter_column('users', 'owner_level',
               existing_type=sa.INTEGER(),
               comment='Уровень владельца канала',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'advertiser_level',
               existing_type=sa.INTEGER(),
               comment='Уровень рекламодателя',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'owner_xp',
               existing_type=sa.INTEGER(),
               comment='XP владельца (за публикации в канале)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'advertiser_xp',
               existing_type=sa.INTEGER(),
               comment='XP рекламодателя (за запуск кампаний)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_table_comment(
        'user_badges',
        existing_comment='Выданные значки пользователей',
        schema=None
    )
    op.alter_column('user_badges', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_badges', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_badges', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('telegram_chats', 'is_accepting_ads',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Канал принимает рекламные размещения',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('telegram_chats', 'price_per_post',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Цена за один рекламный пост в рублях',
               existing_nullable=True)
    op.alter_column('telegram_chats', 'owner_user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Владелец канала (FK на users.id)',
               existing_nullable=True)
    op.alter_column('telegram_chats', 'admin_added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Когда бот был добавлен администратором',
               existing_nullable=True)
    op.alter_column('telegram_chats', 'bot_is_admin',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Бот добавлен администратором в канале',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('telegram_chats', 'recent_posts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Последние 5 постов для LLM-классификации (см. RecentPostJSON)',
               existing_nullable=True)
    op.alter_column('telegram_chats', 'llm_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Уверенность LLM при последней классификации (0.0–1.0)',
               existing_nullable=True)
    op.alter_column('telegram_chats', 'last_classified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Когда последний раз была LLM-классификация',
               existing_nullable=True)
    op.drop_table_comment(
        'reviews',
        existing_comment='Отзывы о размещениях (двусторонняя оценка)',
        schema=None
    )
    op.alter_column('reviews', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('reviews', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('reviews', 'channel_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('reviews', 'reviewee_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('reviews', 'reviewer_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_table_comment(
        'payouts',
        existing_comment='Выплаты владельцам каналов за рекламные размещения',
        schema=None
    )
    op.drop_index(op.f('ix_payouts_placement_id'), table_name='payouts')
    op.create_index(op.f('ix_payouts_placement_id'), 'payouts', ['placement_id'], unique=True)
    op.alter_column('payouts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('payouts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('payouts', 'paid_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('payouts', 'channel_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('payouts', 'owner_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.add_column('mailing_logs', sa.Column('auto_approve_notified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Отправлено ли уведомление за 3 часа до автоодобрения'))
    op.alter_column('mailing_logs', 'rejection_reason',
               existing_type=sa.VARCHAR(length=50),
               comment='Причина отклонения заявки',
               existing_nullable=True)
    op.drop_column('mailing_logs', 'scheduled_at')
    op.drop_table_comment(
        'channel_ratings',
        existing_comment='Ежедневные рейтинги каналов',
        schema=None
    )
    op.alter_column('channel_ratings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('channel_ratings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('channel_ratings', 'channel_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_table_comment(
        'channel_mediakits',
        existing_comment='Медиакиты каналов для привлечения рекламодателей',
        schema=None
    )
    op.drop_index(op.f('ix_channel_mediakits_owner_user_id'), table_name='channel_mediakits')
    op.create_index(op.f('ix_channel_mediakits_owner_id'), 'channel_mediakits', ['owner_user_id'], unique=False)
    op.alter_column('channel_mediakits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('channel_mediakits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_table_comment(
        'badges',
        existing_comment='Каталог значков платформы',
        schema=None
    )
    op.alter_column('badges', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('badges', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_table_comment(
        'badge_achievements',
        existing_comment='Шаблоны достижений для автоматической выдачи значков',
        schema=None
    )
    op.drop_index(op.f('ix_badge_achievements_is_active'), table_name='badge_achievements')
    op.drop_index(op.f('ix_badge_achievements_badge_id'), table_name='badge_achievements')
    op.drop_index(op.f('ix_badge_achievements_achievement_type'), table_name='badge_achievements')
    op.create_index(op.f('ix_badge_achievements_type'), 'badge_achievements', ['achievement_type'], unique=False)
    op.create_index(op.f('ix_badge_achievements_active'), 'badge_achievements', ['is_active'], unique=False)
    op.alter_column('badge_achievements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('badge_achievements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_table_comment(
        'b2b_packages',
        existing_comment='Пакетные предложения B2B-маркетплейса',
        schema=None
    )
    op.alter_column('b2b_packages', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('b2b_packages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('b2b_packages', 'channel_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_table('topic_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_name_ru', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('topic_categories_pkey')),
    sa.UniqueConstraint('topic', 'subcategory', name=op.f('uq_topic_subcategory'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Категории и подкатегории Telegram каналов'
    )
    op.create_index(op.f('ix_topic_categories_topic'), 'topic_categories', ['topic'], unique=False)
    op.create_index(op.f('ix_topic_categories_subcategory'), 'topic_categories', ['subcategory'], unique=False)
    op.create_index(op.f('ix_topic_categories_is_active'), 'topic_categories', ['is_active'], unique=False)
    # ### end Alembic commands ###
