"""
Uploads router — video upload result polling for Mini App.
"""

import json
import logging
from typing import Annotated, Any

from fastapi import APIRouter, Depends

from src.api.dependencies import get_current_user
from src.config.settings import settings

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Uploads"])


@router.get("/video/{session_id}")
async def get_video_upload_result(
    session_id: str,
    _current_user: Annotated[Any, Depends(get_current_user)],
) -> dict:
    """
    Poll for video upload result.

    Mini App polls this endpoint every 2s after the user sends a video via bot deep link.

    Args:
        session_id: Unique session ID generated by the Mini App component.

    Returns:
        {ready: false} if video not yet received, or {ready: true, file_id, duration, thumbnail_file_id}.
    """
    import redis.asyncio as aioredis

    r = aioredis.from_url(str(settings.redis_url))
    try:
        result = await r.get(f"video_result:{session_id}")
    finally:
        await r.close()

    if not result:
        return {"ready": False, "file_id": None, "duration": None, "thumbnail_file_id": None}

    data = json.loads(result)
    return {"ready": True, **data}
