"""Pre-payout gate checkers (G13-G18).

G13: Publication period elapsed (configured display window has passed)
G14: Act of completed services generated
G15: Act signed by both sides (Phase 4 — КЭП)
G16: Tax receipt issued (Phase 4 — Мой налог real integration)
G17: VAT obligation handled
G18: Payout reported to ОРД

5b.6 fills G13/G14 real bodies and G17/G18 Phase 5 pending markers.
G15/G16 remain Phase 4 stubs. None are wired into ``_TRANSITION_GATES``
— payout-side gates hand off to a future PayoutComplianceService
(Phase 5/5b.7) per the comment in ``legal_compliance_service.py``.
"""

from sqlalchemy.ext.asyncio import AsyncSession

from src.core.enums.gate_reason import GateReason
from src.core.enums.placement_gate import PlacementGate
from src.core.schemas.gate_result import GateResult
from src.db.models.placement_request import PlacementRequest
from src.db.repositories.act_repo import ActRepository


async def check_g13(session: AsyncSession, placement: PlacementRequest) -> GateResult:
    """G13_PUBLICATION_PERIOD_ELAPSED.

    Reads ``placement.deleted_at`` as authoritative signal that the
    publication period has elapsed AND the post has been removed by the
    bot. Pairs with G14 — same trigger condition: Act generation
    requires ``deleted_at IS NOT NULL`` (act_service.py).

    Alternative signals (``scheduled_delete_at <= now()``,
    ``published_at + format_duration <= now()``) introduce time math
    and Celery scheduling-lag races without correctness gain;
    ``deleted_at`` is the durable post-deletion signal aligned with
    the placement's ``→ completed`` transition.

    Pattern 1 (S-48): receives session (unused), no commit/flush/rollback.
    """
    if placement.deleted_at is None:
        return GateResult(
            gate=PlacementGate.G13_PUBLICATION_PERIOD_ELAPSED,
            passed=False,
            blocker=True,
            reason_code=GateReason.PUBLICATION_PERIOD_NOT_ELAPSED.value,
            remediation_url=None,
        )
    return GateResult(
        gate=PlacementGate.G13_PUBLICATION_PERIOD_ELAPSED,
        passed=True,
        blocker=True,
        reason_code=GateReason.OK.value,
    )


async def check_g14(session: AsyncSession, placement: PlacementRequest) -> GateResult:
    """G14_ACT_GENERATED.

    Reads ``ActRepository.get_by_placement_request(placement.id)``.
    Pass iff a row exists (Act is single-per-placement: ``ActService``
    early-exits if existing).

    ``Act`` is auto-generated by
    ``publication_service.delete_published_post`` after
    ``placement.deleted_at`` is set. Generation is wrapped in
    try/except — silent failure leaves no Act row. G14 catches that
    case at gate-time. Production-launch hardening should additionally
    proactively alarm on the swallowed exception.

    G15 (ACT_SIGNED_BOTH_SIDES) covers signing flow and stays a
    Phase 4 stub — G14 only checks existence.

    Pattern 1 (S-48): receives session, no commit/flush/rollback.
    """
    act = await ActRepository(session).get_by_placement_request(placement.id)
    if act is None:
        return GateResult(
            gate=PlacementGate.G14_ACT_GENERATED,
            passed=False,
            blocker=True,
            reason_code=GateReason.ACT_NOT_GENERATED.value,
            remediation_url=None,
        )
    return GateResult(
        gate=PlacementGate.G14_ACT_GENERATED,
        passed=True,
        blocker=True,
        reason_code=GateReason.OK.value,
    )


async def check_g15(session: AsyncSession, placement: PlacementRequest) -> GateResult:
    """G15_ACT_SIGNED_BOTH_SIDES — Phase 4 stub."""
    raise NotImplementedError(f"Phase 4: {PlacementGate.G15_ACT_SIGNED_BOTH_SIDES.name}")


async def check_g16(session: AsyncSession, placement: PlacementRequest) -> GateResult:
    """G16_TAX_RECEIPT_ISSUED — Phase 4 stub."""
    raise NotImplementedError(f"Phase 4: {PlacementGate.G16_TAX_RECEIPT_ISSUED.name}")


async def check_g17(session: AsyncSession, placement: PlacementRequest) -> GateResult:
    """G17_VAT_OBLIGATION_HANDLED — Phase 3b stub."""
    raise NotImplementedError(f"Phase 3b: {PlacementGate.G17_VAT_OBLIGATION_HANDLED.name}")


async def check_g18(session: AsyncSession, placement: PlacementRequest) -> GateResult:
    """G18_PAYOUT_REPORTED_TO_ORD — Phase 3b stub."""
    raise NotImplementedError(f"Phase 3b: {PlacementGate.G18_PAYOUT_REPORTED_TO_ORD.name}")
