"""Pre-payout gate checkers (G13-G18).

G13: Publication period elapsed (configured display window has passed)
G14: Act of completed services generated
G15: Act signed by both sides (Phase 4 — КЭП)
G16: Tax receipt issued (Phase 4 — Мой налог real integration)
G17: VAT obligation handled
G18: Payout reported to ОРД

5b.6 fills G13/G14 real bodies and G17/G18 Phase 5 pending markers.
5b.7d fills G15/G16 as Phase 4 pending markers (mirror G17/G18). None
are wired into ``_TRANSITION_GATES`` — payout-side gates remain reserved
for the Phase 5 coordinator that will own PayoutRequest lifecycle.
"""

from sqlalchemy.ext.asyncio import AsyncSession

from src.core.enums.gate_reason import GateReason
from src.core.enums.placement_gate import PlacementGate
from src.core.schemas.gate_result import GateResult
from src.db.models.placement_request import PlacementRequest
from src.db.repositories.act_repo import ActRepository


async def check_g13(session: AsyncSession, placement: PlacementRequest) -> GateResult:
    """G13_PUBLICATION_PERIOD_ELAPSED.

    Reads ``placement.deleted_at`` as authoritative signal that the
    publication period has elapsed AND the post has been removed by the
    bot. Pairs with G14 — same trigger condition: Act generation
    requires ``deleted_at IS NOT NULL`` (act_service.py).

    Alternative signals (``scheduled_delete_at <= now()``,
    ``published_at + format_duration <= now()``) introduce time math
    and Celery scheduling-lag races without correctness gain;
    ``deleted_at`` is the durable post-deletion signal aligned with
    the placement's ``→ completed`` transition.

    Pattern 1 (S-48): receives session (unused), no commit/flush/rollback.
    """
    if placement.deleted_at is None:
        return GateResult(
            gate=PlacementGate.G13_PUBLICATION_PERIOD_ELAPSED,
            passed=False,
            blocker=True,
            reason_code=GateReason.PUBLICATION_PERIOD_NOT_ELAPSED.value,
            remediation_url=None,
        )
    return GateResult(
        gate=PlacementGate.G13_PUBLICATION_PERIOD_ELAPSED,
        passed=True,
        blocker=True,
        reason_code=GateReason.OK.value,
    )


async def check_g14(session: AsyncSession, placement: PlacementRequest) -> GateResult:
    """G14_ACT_GENERATED.

    Reads ``ActRepository.get_by_placement_request(placement.id)``.
    Pass iff a row exists (Act is single-per-placement: ``ActService``
    early-exits if existing).

    ``Act`` is auto-generated by
    ``publication_service.delete_published_post`` after
    ``placement.deleted_at`` is set. Generation is wrapped in
    try/except — silent failure leaves no Act row. G14 catches that
    case at gate-time. Production-launch hardening should additionally
    proactively alarm on the swallowed exception.

    G15 (ACT_SIGNED_BOTH_SIDES) covers signing flow and stays a
    Phase 4 stub — G14 only checks existence.

    Pattern 1 (S-48): receives session, no commit/flush/rollback.
    """
    act = await ActRepository(session).get_by_placement_request(placement.id)
    if act is None:
        return GateResult(
            gate=PlacementGate.G14_ACT_GENERATED,
            passed=False,
            blocker=True,
            reason_code=GateReason.ACT_NOT_GENERATED.value,
            remediation_url=None,
        )
    return GateResult(
        gate=PlacementGate.G14_ACT_GENERATED,
        passed=True,
        blocker=True,
        reason_code=GateReason.OK.value,
    )


async def check_g15(session: AsyncSession, placement: PlacementRequest) -> GateResult:
    """G15_ACT_SIGNED_BOTH_SIDES — Phase 4 pending marker.

    Per plan §3.B.1, follows G14 (Act generated) in the pre-payout chain.
    Real body — verify Act has both advertiser-side and owner-side
    signatures via КЭП — is Phase 4 territory (МES Acts API + КЭП
    crypto integration).

    Pattern 1 (S-48): receives session (unused), no commit/flush/rollback.
    """
    return GateResult(
        gate=PlacementGate.G15_ACT_SIGNED_BOTH_SIDES,
        passed=False,
        blocker=True,
        reason_code=GateReason.PHASE4_PENDING.value,
        remediation_url=None,
    )


async def check_g16(session: AsyncSession, placement: PlacementRequest) -> GateResult:
    """G16_TAX_RECEIPT_ISSUED — Phase 4 pending marker.

    Per plan §3.B.1, applies to self-employed owners (receipt issuance
    via Мой налог). Real body — call Мой налог real provider, verify
    receipt accepted with persistent receipt-id — is Phase 4 territory
    (replaces current synthetic receipt-id flow).

    Pattern 1 (S-48): receives session (unused), no commit/flush/rollback.
    """
    return GateResult(
        gate=PlacementGate.G16_TAX_RECEIPT_ISSUED,
        passed=False,
        blocker=True,
        reason_code=GateReason.PHASE4_PENDING.value,
        remediation_url=None,
    )


async def check_g17(session: AsyncSession, placement: PlacementRequest) -> GateResult:
    """G17_VAT_OBLIGATION_HANDLED — Phase 5 pending marker.

    Per plan §3.B.1, applies only to ``legal_entity`` owners
    (счёт-фактура generation with VAT). Real body — Invoice generation
    + VAT calculation + signed-LE-counterparty check — is Phase 5
    territory per 5b.1 closure CHANGES (Payout Provider Implementation
    phase absorbs G16/G17/G18 bodies).

    Conditional pre-check on ``owner.legal_status`` is deliberately
    deferred: Phase 5 will replace this body end-to-end with the real
    conditional + Invoice integration, so the interim marker is
    unconditional to keep 5b.6 surface minimal.

    Pattern 1 (S-48): receives session (unused), no commit/flush/rollback.
    """
    return GateResult(
        gate=PlacementGate.G17_VAT_OBLIGATION_HANDLED,
        passed=False,
        blocker=True,
        reason_code=GateReason.PHASE5_PENDING.value,
        remediation_url=None,
    )


async def check_g18(session: AsyncSession, placement: PlacementRequest) -> GateResult:
    """G18_PAYOUT_REPORTED_TO_ORD — Phase 5 pending marker.

    Per plan §3.B.1, applies if monthly advertising turnover exceeds
    the ФЗ-38 threshold N. Real body requires:

    - Real ORD provider (Phase 6 §6.B.3 hardens StubOrdProvider)
    - Monthly turnover aggregation across owner placements
    - Threshold constant N (undefined in code today)
    - ORD payout-event report endpoint integration

    Per 5b.1 closure CHANGES, Phase 5 (Payout Provider Implementation)
    absorbs this body. Marker reuses ``PHASE5_PENDING`` (mirror G06 /
    G17) — keeps gate registry consistent and surfaces phase boundary
    to API consumers.

    Pattern 1 (S-48): receives session (unused), no commit/flush/rollback.
    """
    return GateResult(
        gate=PlacementGate.G18_PAYOUT_REPORTED_TO_ORD,
        passed=False,
        blocker=True,
        reason_code=GateReason.PHASE5_PENDING.value,
        remediation_url=None,
    )
